export const CHNAGE_USER_INFO = 'CHNAGE_USER_INFO'
export const CHNAGE_USER_TOKEN = 'CHNAGE_USER_TOKEN'
export const CHNAGE_USER_IDENTITY = 'CHNAGE_USER_IDENTITY'

// 购物车
export const CHANGE_SHOP_CAR_INFO = 'CHANGE_SHOP_CAR_INFO'
export const CHANGE_SHOP_CAR_MODE = 'CHANGE_SHOP_CAR_MODE'
export const CHANGE_DELETE_LIST = 'CHANGE_DELETE_LIST'
export const ADD_DELETE_ITEM = 'ADD_DELETE_ITEM'
export const BATCH_GOODS_DELETE = 'BATCH_GOODS_DELETE'

// 位置
export const CHANGE_LOCATION_INFO = 'CHANGE_LOCATION_INFO'
export const CHANGE_LOACTION_DETAIL_INFO = 'CHANGE_LOACTION_DETAIL_INFO'

// 客服
export const CHANGE_CUSTOMER_SERVICE_INFO = 'CHANGE_CUSTOMER_SERVICE_INFO'
export const CHANGE_WSINFO_INFO = 'CHANGE_WSINFO_INFO'
export const CHANGE_WS_INFO = 'CHANGE_WS_INFO'
export const CHANGE_CHAT_LIST = 'CHANGE_CHAT_LIST'
export const CHANGE_ON_FN = 'CHANGE_ON_FN'

// 个人中心
export const CHNAGE_PRICE_PLATFORM_INFO = 'CHNAGE_PRICE_PLATFORM_INFO'
export const CHNAGE_SHOP_CAR_NUMBER = 'CHNAGE_SHOP_CAR_NUMBER'
export const CHNAGE_LEVEL_TYPE = 'CHNAGE_LEVEL_TYPE'

// 社区
export const CHANGE_HOME_PAGE_IMAGE = 'change_home_page_image'
export const CHANGE_HOME_STORE = 'CHANGE_HOME_STORE'
export const CHANGE_HOME_PAGE_IMAGE_PATH = 'CHANGE_HOME_PAGE_IMAGE_PATH'
export const CHANGE_DZ_VIP_PACKAGE = 'CHANGE_DZ_VIP_PACKAGE'

// app
export const CHANGE_IS_IN_MINIPROGRAM = 'CHANGE_IS_IN_MINIPROGRAM'
export const CHANGE_SYSTERM_INFO = 'CHANGE_SYSTERM_INFO'
export const CHANGE_SYSTERM_TERMINAL = 'CHANGE_SYSTERM_TERMINAL'
